/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencias;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author danflovier
 */
public class Contraseña extends javax.swing.JFrame {
    
    public Contraseña() {
        initComponents();
        
        // Set a background color to the JFrame
        this.getContentPane().setBackground(new Color(33,150,243));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field_correo = new javax.swing.JTextField();
        label_matricula = new javax.swing.JLabel();
        label_login = new javax.swing.JLabel();
        button_iniciar = new javax.swing.JButton();
        background_white1 = new javax.swing.JLabel();
        label_residencias = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        log_out = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        about_csf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Residencias Santa Fe | Correo");
        setBackground(new java.awt.Color(33, 150, 243));
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage());
        setMinimumSize(new java.awt.Dimension(716, 666));
        setPreferredSize(new java.awt.Dimension(716, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(716, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        field_correo.setBackground(new java.awt.Color(223, 223, 223));
        field_correo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        field_correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field_correo.setToolTipText("");
        field_correo.setBorder(null);
        field_correo.setDoubleBuffered(true);
        getContentPane().add(field_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 330, 30));

        label_matricula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_matricula.setForeground(new java.awt.Color(76, 76, 76));
        label_matricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_matricula.setText("INGRESA TU CORREO:");
        getContentPane().add(label_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 330, -1));

        label_login.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label_login.setForeground(new java.awt.Color(76, 76, 76));
        label_login.setText("RECUPERAR CONTRASEÑA");
        getContentPane().add(label_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        button_iniciar.setBackground(new java.awt.Color(26, 188, 156));
        button_iniciar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        button_iniciar.setText("ENVIAR");
        button_iniciar.setBorder(null);
        button_iniciar.setBorderPainted(false);
        button_iniciar.setContentAreaFilled(false);
        button_iniciar.setOpaque(true);
        button_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(button_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 330, 50));

        background_white1.setBackground(new java.awt.Color(255, 255, 255));
        background_white1.setForeground(new java.awt.Color(3, 169, 244));
        background_white1.setOpaque(true);
        getContentPane().add(background_white1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 530, 450));

        label_residencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_residencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo3.png"))); // NOI18N
        getContentPane().add(label_residencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 180, 70));

        back.setBackground(java.awt.Color.white);
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back-button_white.png"))); // NOI18N
        back.setText("REGRESAR");
        back.setBorder(null);
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setMaximumSize(new java.awt.Dimension(129, 65));
        back.setMinimumSize(new java.awt.Dimension(129, 65));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 130, 40));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setBorder(null);
        Menu.setBorderPainted(false);
        Menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        file.setText("File");
        file.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        log_out.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        log_out.setText("Cerrar sesión");
        log_out.setBorderPainted(true);
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        file.add(log_out);

        Menu.add(file);

        about.setText("About...");
        about.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        about_csf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        about_csf.setText("Residencias CSF");
        about_csf.setBorderPainted(true);
        about_csf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_csfActionPerformed(evt);
            }
        });
        about.add(about_csf);

        Menu.add(about);

        setJMenuBar(Menu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_log_outActionPerformed

    private void about_csfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_csfActionPerformed
        new ResidenciasCSF().setVisible(true);
    }//GEN-LAST:event_about_csfActionPerformed

    private void button_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_iniciarActionPerformed
        Properties props = new Properties();
            // Hostname
            //props.put("mail.smtp.host", server.getSelectedItem());
            props.put("mail.smtp.host", "smtp.gmail.com");
            
            // Protocol
            props.put("mail.transport.protocol", "smtp");
            
            // TTLS
            props.put("mail.smtp.starttls.enable", "true");
            
            // Authorize
            props.put("mail.smtp.auth", "true");
            
            // SMTP Port
            props.put("mail.smtp.port", "465");
            
            // SSL Port
            props.put("mail.smtp.socketFactory.port", "465");
            props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
            
            // Start session from the properties
            Session session = Session.getDefaultInstance(props);
            
            // Try to send email if allthe fields of data are filled
            //if (server.getSelectedItem() != "Seleccionar" && field_from.getText() != null && field_to.getText() != null && field_subject.getText() != null && text_message != null && field_password != null){
            if (!"".equals(field_correo.getText())){
                
                try {
                    String contraseña = "abcd";
                    InternetAddress fromAddress = new InternetAddress("residencias.csf2017@gmail.com");
                    InternetAddress toAddress = new InternetAddress(field_correo.getText());

                    Message message = new MimeMessage(session);
                    message.setFrom(fromAddress);
                    message.setRecipient(Message.RecipientType.TO, toAddress);
                    message.setSubject("Residencias CSF | Recuperación de contraseña");
                    message.setText("Estimado usuario.\nLa contraseña de su usuario es: " + contraseña);
                    
                    String email = "residencias.csf2017@gmail.com";
                    String username = email.replace("@gmail.com","");
                    
                    // Send the message
                    Transport.send(message, username, new String("Residencias2017"));
                    JOptionPane.showMessageDialog(this,"Mensaje enviado con éxito.","ÉXITO",JOptionPane.INFORMATION_MESSAGE);
                    
                    field_correo.setText("");
                    
                } 
                catch (MessagingException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this,"Lo sentimos, el mensaje no ha sido enviado. Intente de nuevo.","ERROR",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Llena los campos correctamente.","ERROR",JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_button_iniciarActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu about;
    private javax.swing.JMenuItem about_csf;
    private javax.swing.JButton back;
    private javax.swing.JLabel background_white1;
    private javax.swing.JButton button_iniciar;
    private javax.swing.JTextField field_correo;
    private javax.swing.JMenu file;
    private javax.swing.JLabel label_login;
    private javax.swing.JLabel label_matricula;
    private javax.swing.JLabel label_residencias;
    private javax.swing.JMenuItem log_out;
    // End of variables declaration//GEN-END:variables
}
