/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencias;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author danflovier
 */
public class CorreoBackup extends javax.swing.JFrame {
    
    public CorreoBackup() {
        initComponents();
        
        // Get the screen resolution of the device
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        
        // Set size of the JFrame
        this.setSize(screenWidth / 2 - 150, screenHeight - 200);
        
        // Set default close operation
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        
        // Set a background color to the JFrame
        this.getContentPane().setBackground(new Color(255,255,255));
        
        // Center the JFrame
        this.setLocationRelativeTo(null);
        
        // Delete border from the textArea
        scrollPane_message.setBorder(null);
        
        field_subject.setText("Residencias Campus Santa Fe | Caso de Indisciplina del alumno");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_to = new javax.swing.JLabel();
        label_from = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        label_correo = new javax.swing.JLabel();
        label_message = new javax.swing.JLabel();
        label_logo = new javax.swing.JLabel();
        label_subject1 = new javax.swing.JLabel();
        label_smtp = new javax.swing.JLabel();
        label_confirmation = new javax.swing.JLabel();
        label_line1 = new javax.swing.JLabel();
        label_line = new javax.swing.JLabel();
        field_from = new javax.swing.JTextField();
        field_to = new javax.swing.JTextField();
        field_subject = new javax.swing.JTextField();
        field_password = new javax.swing.JPasswordField();
        server = new javax.swing.JComboBox<>();
        scrollPane_message = new javax.swing.JScrollPane();
        text_message = new javax.swing.JTextArea();
        button_send = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Residencias Santa Fe | Correo");
        setBackground(new java.awt.Color(33, 150, 243));
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage());
        setResizable(false);
        setSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_to.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_to.setForeground(new java.awt.Color(76, 76, 76));
        label_to.setText("PARA");
        getContentPane().add(label_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        label_from.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_from.setForeground(new java.awt.Color(76, 76, 76));
        label_from.setText("DE");
        getContentPane().add(label_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        label_password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_password.setForeground(new java.awt.Color(76, 76, 76));
        label_password.setText("CONTRASEÑA");
        getContentPane().add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, 130, -1));

        label_correo.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        label_correo.setForeground(new java.awt.Color(76, 76, 76));
        label_correo.setText("CORREO");
        getContentPane().add(label_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        label_message.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_message.setForeground(new java.awt.Color(76, 76, 76));
        label_message.setText("MENSAJE");
        getContentPane().add(label_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        label_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo5.png"))); // NOI18N
        getContentPane().add(label_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 750, 180, 70));

        label_subject1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_subject1.setForeground(new java.awt.Color(76, 76, 76));
        label_subject1.setText("ASUNTO");
        getContentPane().add(label_subject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        label_smtp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_smtp.setForeground(new java.awt.Color(76, 76, 76));
        label_smtp.setText("SMTP SERVER");
        getContentPane().add(label_smtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        label_confirmation.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_confirmation.setForeground(new java.awt.Color(76, 76, 76));
        label_confirmation.setText("CONFIRMACIÓN");
        getContentPane().add(label_confirmation, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));

        label_line1.setBackground(new java.awt.Color(250, 197, 28));
        label_line1.setForeground(new java.awt.Color(3, 169, 244));
        label_line1.setOpaque(true);
        getContentPane().add(label_line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 500, 10));

        label_line.setBackground(new java.awt.Color(250, 197, 28));
        label_line.setForeground(new java.awt.Color(3, 169, 244));
        label_line.setOpaque(true);
        getContentPane().add(label_line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 250, 10));

        field_from.setBackground(new java.awt.Color(223, 223, 223));
        field_from.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        field_from.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field_from.setToolTipText("");
        field_from.setBorder(null);
        field_from.setDoubleBuffered(true);
        getContentPane().add(field_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 330, 30));

        field_to.setBackground(new java.awt.Color(223, 223, 223));
        field_to.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        field_to.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field_to.setToolTipText("");
        field_to.setBorder(null);
        field_to.setDoubleBuffered(true);
        getContentPane().add(field_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 330, 30));

        field_subject.setBackground(new java.awt.Color(223, 223, 223));
        field_subject.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        field_subject.setToolTipText("");
        field_subject.setBorder(null);
        field_subject.setDoubleBuffered(true);
        getContentPane().add(field_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 560, 30));

        field_password.setBackground(new java.awt.Color(223, 223, 223));
        field_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field_password.setBorder(null);
        getContentPane().add(field_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 720, 190, 30));

        server.setBackground(new java.awt.Color(204, 204, 204));
        server.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        server.setForeground(new java.awt.Color(76, 76, 76));
        server.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "smtp.gmail.com" }));
        server.setBorder(null);
        server.setFocusable(false);
        server.setLightWeightPopupEnabled(false);
        server.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverActionPerformed(evt);
            }
        });
        getContentPane().add(server, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 210, 30));

        text_message.setBackground(new java.awt.Color(223, 223, 223));
        text_message.setColumns(20);
        text_message.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_message.setRows(5);
        text_message.setBorder(null);
        text_message.setCaretColor(new java.awt.Color(223, 223, 223));
        scrollPane_message.setViewportView(text_message);

        getContentPane().add(scrollPane_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 560, 180));

        button_send.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        button_send.setForeground(new java.awt.Color(76, 76, 76));
        button_send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/send.png"))); // NOI18N
        button_send.setText("ENVIAR");
        button_send.setBorder(null);
        button_send.setBorderPainted(false);
        button_send.setContentAreaFilled(false);
        button_send.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_send.setMaximumSize(new java.awt.Dimension(129, 65));
        button_send.setMinimumSize(new java.awt.Dimension(129, 65));
        button_send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isEmailCursorEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isEmailCursorExited(evt);
            }
        });
        button_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sendActionPerformed(evt);
            }
        });
        getContentPane().add(button_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 760, 190, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sendActionPerformed
            Properties props = new Properties();
            // Hostname
            props.put("mail.smtp.host", server.getSelectedItem());
            //props.put("mail.smtp.host", "smtp.gmail.com");
            
            // Protocol
            props.put("mail.transport.protocol", "smtp");
            
            // TTLS
            props.put("mail.smtp.starttls.enable", "true");
            
            // Authorize
            props.put("mail.smtp.auth", "true");
            
            // SMTP Port
            props.put("mail.smtp.port", "465");
            
            // SSL Port
            props.put("mail.smtp.socketFactory.port", "465");
            props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
            
            // Start session from the properties
            Session session = Session.getDefaultInstance(props);
            
            // Try to send email if allthe fields of data are filled
            //if (server.getSelectedItem() != "Seleccionar" && field_from.getText() != null && field_to.getText() != null && field_subject.getText() != null && text_message != null && field_password != null){
            if (server.getSelectedItem() != "Seleccionar" && field_from.getText() != null && field_to.getText() != null && field_subject.getText() != null && text_message != null && field_password != null){
                
                try {
                    InternetAddress fromAddress = new InternetAddress(field_from.getText());
                    InternetAddress toAddress = new InternetAddress(field_to.getText());

                    Message message = new MimeMessage(session);
                    message.setFrom(fromAddress);
                    message.setRecipient(Message.RecipientType.TO, toAddress);
                    message.setSubject(field_subject.getText());
                    message.setText(text_message.getText());
                    
                    String email = field_from.getText();
                    String username = email.replace("@gmail.com","");
                    
                    // Send the message
                    Transport.send(message, username, new String(field_password.getPassword()));
                    JOptionPane.showMessageDialog(this,"Mensaje enviado con éxito.","ÉXITO",JOptionPane.INFORMATION_MESSAGE);

                } 
                catch (MessagingException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this,"Lo sentimos, el mensaje no ha sido enviado. Intente de nuevo.","ERROR",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Llena los campos correctamente.","ERROR",JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_button_sendActionPerformed

    private void serverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverActionPerformed
        Object object = server.getSelectedItem();
        String response = object.toString();
    
        if (response == "smtp.gmail.com"){
            field_from.setText("residencias.csf2017@gmail.com");
            field_to.setText("@gmail.com");
        }
    }//GEN-LAST:event_serverActionPerformed

    private void isEmailCursorEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isEmailCursorEntered
       button_send.setForeground(new Color(220,220,220));
    }//GEN-LAST:event_isEmailCursorEntered

    private void isEmailCursorExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isEmailCursorExited
      button_send.setForeground(new Color(76,76,76));
    }//GEN-LAST:event_isEmailCursorExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorreoBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorreoBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorreoBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorreoBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CorreoBackup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_send;
    private javax.swing.JTextField field_from;
    private javax.swing.JPasswordField field_password;
    private javax.swing.JTextField field_subject;
    private javax.swing.JTextField field_to;
    private javax.swing.JLabel label_confirmation;
    private javax.swing.JLabel label_correo;
    private javax.swing.JLabel label_from;
    private javax.swing.JLabel label_line;
    private javax.swing.JLabel label_line1;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_message;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_smtp;
    private javax.swing.JLabel label_subject1;
    private javax.swing.JLabel label_to;
    private javax.swing.JScrollPane scrollPane_message;
    private javax.swing.JComboBox<String> server;
    private javax.swing.JTextArea text_message;
    // End of variables declaration//GEN-END:variables
}
