/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencias;

import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danflovier
 */
public class HistorialAcademico extends javax.swing.JFrame {
    Connection con;
    final private MySQL db;
    
    public HistorialAcademico() {
        initComponents();
        
        // Set a background color to the JFrame
        this.getContentPane().setBackground(new Color(255,255,255));  
        
        db = new MySQL();
        
        initMatricula();
    }
    
    public void initMatricula(){
        con = db.MySQLConnection();
        String query = "{call getAlumnos()}";
        ResultSet result;
        try {
            CallableStatement st = con.prepareCall(query);
            result = st.executeQuery();
            while(result.next()){
                matricula.addItem(result.getString("Matricula"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Alumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void clearForm(){
        semestre_a.setSelectedIndex(0);
        promedio_a.setText("");
        promedio_acum.setText("");
        matricula.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_id = new javax.swing.JLabel();
        label_login = new javax.swing.JLabel();
        label_buscar = new javax.swing.JLabel();
        label_logo = new javax.swing.JLabel();
        label_line = new javax.swing.JLabel();
        label_semestre = new javax.swing.JLabel();
        label_promedio_actual = new javax.swing.JLabel();
        label_promedio_acumulado = new javax.swing.JLabel();
        promedio_a = new javax.swing.JTextField();
        buscar_historial = new javax.swing.JTextField();
        promedio_acum = new javax.swing.JTextField();
        semestre_a = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_historial = new javax.swing.JTable();
        registrar = new javax.swing.JButton();
        buscar1 = new javax.swing.JButton();
        buscar2 = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        mostrar_todos = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        back = new javax.swing.JButton();
        matricula = new javax.swing.JComboBox<>();
        Menu = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        log_out = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        about_csf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Residencias Santa Fe | Historial Académico");
        setBackground(new java.awt.Color(33, 150, 243));
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage());
        setPreferredSize(new java.awt.Dimension(1240, 680));
        setResizable(false);
        setSize(new java.awt.Dimension(1240, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_id.setForeground(new java.awt.Color(76, 76, 76));
        label_id.setText("MATRÍCULA DEL ALUMNO:");
        getContentPane().add(label_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        label_login.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        label_login.setForeground(new java.awt.Color(76, 76, 76));
        label_login.setText("HISTORIAL ACADÉMICO");
        getContentPane().add(label_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        label_buscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_buscar.setForeground(new java.awt.Color(76, 76, 76));
        label_buscar.setText("BUSCAR HISTORIAL:");
        getContentPane().add(label_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        label_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo5.png"))); // NOI18N
        getContentPane().add(label_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 540, 180, 70));

        label_line.setBackground(new java.awt.Color(233, 30, 99));
        label_line.setForeground(new java.awt.Color(3, 169, 244));
        label_line.setOpaque(true);
        getContentPane().add(label_line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 890, 10));

        label_semestre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_semestre.setForeground(new java.awt.Color(76, 76, 76));
        label_semestre.setText("SEMESTRE ACTUAL");
        getContentPane().add(label_semestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 220, -1));

        label_promedio_actual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_promedio_actual.setForeground(new java.awt.Color(76, 76, 76));
        label_promedio_actual.setText("PROMEDIO ACTUAL");
        getContentPane().add(label_promedio_actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 220, -1));

        label_promedio_acumulado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_promedio_acumulado.setForeground(new java.awt.Color(76, 76, 76));
        label_promedio_acumulado.setText("PROMEDIO ACUMULADO");
        getContentPane().add(label_promedio_acumulado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 230, -1));

        promedio_a.setBackground(new java.awt.Color(223, 223, 223));
        promedio_a.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        promedio_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        promedio_a.setToolTipText("");
        promedio_a.setBorder(null);
        promedio_a.setDoubleBuffered(true);
        promedio_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                promedio_auserIsMouseExited(evt);
            }
        });
        getContentPane().add(promedio_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 220, 30));

        buscar_historial.setBackground(new java.awt.Color(223, 223, 223));
        buscar_historial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buscar_historial.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        buscar_historial.setToolTipText("");
        buscar_historial.setBorder(null);
        buscar_historial.setDoubleBuffered(true);
        getContentPane().add(buscar_historial, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 200, 30));

        promedio_acum.setBackground(new java.awt.Color(223, 223, 223));
        promedio_acum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        promedio_acum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        promedio_acum.setToolTipText("");
        promedio_acum.setBorder(null);
        promedio_acum.setDoubleBuffered(true);
        getContentPane().add(promedio_acum, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 220, 30));

        semestre_a.setBackground(new java.awt.Color(204, 204, 204));
        semestre_a.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        semestre_a.setForeground(new java.awt.Color(76, 76, 76));
        semestre_a.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        semestre_a.setBorder(null);
        semestre_a.setFocusable(false);
        semestre_a.setLightWeightPopupEnabled(false);
        getContentPane().add(semestre_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 220, 30));

        tabla_historial.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tabla_historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SEMESTRE ACTUAL", "PROMEDIO ACTUAL", "PROMEDIO ACUMULADO"
            }
        ));
        jScrollPane1.setViewportView(tabla_historial);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 360, 260));

        registrar.setBackground(new java.awt.Color(255, 255, 255));
        registrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registrar.png"))); // NOI18N
        registrar.setText("REGISTRAR");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 130, 40));

        buscar1.setBackground(new java.awt.Color(255, 255, 255));
        buscar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        buscar1.setText("BUSCAR");
        buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 130, 40));

        buscar2.setBackground(new java.awt.Color(255, 255, 255));
        buscar2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        buscar2.setText("BUSCAR");
        buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar2ActionPerformed(evt);
            }
        });
        getContentPane().add(buscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 140, 30));

        cancelar.setBackground(new java.awt.Color(255, 255, 255));
        cancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 130, 40));

        mostrar_todos.setBackground(new java.awt.Color(255, 255, 255));
        mostrar_todos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mostrar_todos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista.png"))); // NOI18N
        mostrar_todos.setText("MOSTRAR");
        mostrar_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrar_todosActionPerformed(evt);
            }
        });
        getContentPane().add(mostrar_todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, 180, 60));

        eliminar.setBackground(new java.awt.Color(255, 255, 255));
        eliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 340, 180, 60));

        modificar.setBackground(new java.awt.Color(255, 255, 255));
        modificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        modificar.setText("MODIFICAR");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 130, 40));

        back.setBackground(java.awt.Color.white);
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(76, 76, 76));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back-button.png"))); // NOI18N
        back.setText("REGRESAR");
        back.setBorder(null);
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setMaximumSize(new java.awt.Dimension(129, 65));
        back.setMinimumSize(new java.awt.Dimension(129, 65));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 130, 40));

        matricula.setBackground(new java.awt.Color(204, 204, 204));
        matricula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        matricula.setForeground(new java.awt.Color(76, 76, 76));
        matricula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        matricula.setBorder(null);
        matricula.setFocusable(false);
        matricula.setLightWeightPopupEnabled(false);
        getContentPane().add(matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 240, 30));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setBorder(null);
        Menu.setBorderPainted(false);
        Menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        file.setText("File");
        file.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        log_out.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        log_out.setText("Cerrar sesión");
        log_out.setBorderPainted(true);
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        file.add(log_out);

        Menu.add(file);

        about.setText("About...");
        about.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        about_csf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        about_csf.setText("Residencias CSF");
        about_csf.setBorderPainted(true);
        about_csf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_csfActionPerformed(evt);
            }
        });
        about.add(about_csf);

        Menu.add(about);

        setJMenuBar(Menu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void promedio_auserIsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promedio_auserIsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_promedio_auserIsMouseExited

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        String query;
        con = db.MySQLConnection();
        CallableStatement st;
        
        String str = semestre_a.getSelectedItem().toString();
        int semestre_actual = Integer.parseInt(str);
        float promedio_actual = Float.parseFloat(promedio_a.getText());
        float promedio_acumulado = Float.parseFloat(promedio_acum.getText());
        String matricula_alumno = matricula.getSelectedItem().toString();
        
                query = "{call registrarHAcademico(?,?,?,?)}";
                try {
                    st = con.prepareCall(query);
                    st.setInt(1,semestre_actual);
                    st.setFloat(2,promedio_actual);
                    st.setFloat(3,promedio_acumulado);
                    st.setString(4,matricula_alumno);
                    st.executeQuery();
                JOptionPane.showMessageDialog(null, "Historial académico registrado correctamente", "Registro del historial académico", JOptionPane.INFORMATION_MESSAGE);
                clearForm();

            } catch (SQLException ex) {
                Logger.getLogger(Alumnos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_registrarActionPerformed

    private void buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar1ActionPerformed

        if (!matricula.getSelectedItem().equals("Seleccionar") && !semestre_a.getSelectedItem().equals("Seleccionar") && !promedio_a.getText().equals("") && !promedio_acum.getText().equals("")){
            semestre_a.setSelectedIndex(0);
            promedio_a.setText("");
            promedio_acum.setText("");
        }

        if(matricula.getSelectedItem().equals("Seleccionar"))
            JOptionPane.showMessageDialog(null, "Ingrese una matrícula a buscar");
        else{
            Connection connect = db.MySQLConnection();
            String query = "{call getHAcademico(?)}";
            String alumno = matricula.getSelectedItem().toString();
            ResultSet result;
            CallableStatement call;
            
            try {
                call = connect.prepareCall(query);
                call.setString(1, alumno);
                result = call.executeQuery();
                while (result.next()) {
                    semestre_a.setSelectedItem(result.getString("Semestre actual"));
                    promedio_a.setText(result.getString("Promedio actual"));
                    promedio_acum.setText(result.getString("Promedio acumulado"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Alumnos.class.getName()).log(Level.SEVERE, null, ex);
                
            }
        }
    }//GEN-LAST:event_buscar1ActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        clearForm();
    }//GEN-LAST:event_cancelarActionPerformed

    private void buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar2ActionPerformed
        con = db.MySQLConnection();
        
        String query = "{call getHAcademico(?)}";
        ResultSet result;
        String alumno = buscar_historial.getText();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("SEMESTRE ACTUAL");
        modelo.addColumn("PROMEDIO ACTUAL");
        modelo.addColumn("PROMEDIO ACUMULADO");
        modelo.addColumn("ID_EXPEDIENTE");
        
        tabla_historial.setModel(modelo);
        
        String [] datosHAcademico = new String[11];
        
        try {
            CallableStatement call = con.prepareCall(query);
            call.setString(1, alumno);
            result = call.executeQuery();
            while(result.next()){
                datosHAcademico[0] = result.getString("ID_hacademico");
                datosHAcademico[1] = String.valueOf(result.getInt("Semestre actual"));
                datosHAcademico[2] = String.valueOf(result.getFloat("Promedio actual"));
                datosHAcademico[3] = String.valueOf(result.getFloat("Promedio acumulado"));
                datosHAcademico[4] = result.getString("EXPEDIENTE_ID_EXPEDIENTE");
            }
            modelo.addRow(datosHAcademico);
            tabla_historial.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscar2ActionPerformed

    private void mostrar_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_todosActionPerformed
        con = db.MySQLConnection();
        String query = "{call getHAcademicos()}";
        ResultSet result;
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("SEMESTRE ACTUAL");
        modelo.addColumn("PROMEDIO ACTUAL");
        modelo.addColumn("PROMEDIO ACUMULADO");
        modelo.addColumn("ID_EXPEDIENTE");
        
        tabla_historial.setModel(modelo);
        
        String [] datosHAcademico = new String[11];
        try {
            CallableStatement call = con.prepareCall(query);
            result = call.executeQuery();
            while(result.next()){
                datosHAcademico[0] = result.getString("ID_hacademico");
                datosHAcademico[1] = String.valueOf(result.getInt("Semestre actual"));
                datosHAcademico[2] = String.valueOf(result.getFloat("Promedio actual"));
                datosHAcademico[3] = String.valueOf(result.getFloat("Promedio acumulado"));
                datosHAcademico[4] = result.getString("EXPEDIENTE_ID_EXPEDIENTE");
                
                modelo.addRow(datosHAcademico);
                tabla_historial.setModel(modelo);                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mostrar_todosActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        con = db.MySQLConnection();
        String query = "{call eliminarHAcademico(?) }";
        try {
            CallableStatement st = con.prepareCall(query);
            String id_hacademico = (String) tabla_historial.getValueAt(tabla_historial.getSelectedRow(), 4);
            st.setString(1, id_hacademico );
            st.executeQuery();
            mostrar_todos.doClick();
        } catch (SQLException ex) {
            Logger.getLogger(Alumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        String query;
        con = db.MySQLConnection();
        CallableStatement st;
        
        String str = semestre_a.getSelectedItem().toString();
        int semestre_actual = Integer.parseInt(str);
        float promedio_actual = Float.parseFloat(promedio_a.getText());
        float promedio_acumulado = Float.parseFloat(promedio_acum.getText());
        String matricula_alumno = matricula.getSelectedItem().toString();
        
        query = "{call modificarHAcademico(?,?,?,?)}";
            try {
                st = con.prepareCall(query);
                st.setInt(1,semestre_actual);
                st.setFloat(2,promedio_actual);
                st.setFloat(3,promedio_acumulado);
                st.setString(4,matricula_alumno);
                st.executeQuery();
                JOptionPane.showMessageDialog(null, "Historial académico actualizado correctamente", "Modificación del historial académico", JOptionPane.INFORMATION_MESSAGE);
                clearForm();

            } catch (SQLException ex) {
                Logger.getLogger(Alumnos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_modificarActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_log_outActionPerformed

    private void about_csfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_csfActionPerformed
        new ResidenciasCSF().setVisible(true);
    }//GEN-LAST:event_about_csfActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new MenuExpediente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialAcademico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu about;
    private javax.swing.JMenuItem about_csf;
    private javax.swing.JButton back;
    private javax.swing.JButton buscar1;
    private javax.swing.JButton buscar2;
    private javax.swing.JTextField buscar_historial;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton eliminar;
    private javax.swing.JMenu file;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_buscar;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_line;
    private javax.swing.JLabel label_login;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_promedio_actual;
    private javax.swing.JLabel label_promedio_acumulado;
    private javax.swing.JLabel label_semestre;
    private javax.swing.JMenuItem log_out;
    private javax.swing.JComboBox<String> matricula;
    private javax.swing.JButton modificar;
    private javax.swing.JButton mostrar_todos;
    private javax.swing.JTextField promedio_a;
    private javax.swing.JTextField promedio_acum;
    private javax.swing.JButton registrar;
    private javax.swing.JComboBox<String> semestre_a;
    private javax.swing.JTable tabla_historial;
    // End of variables declaration//GEN-END:variables
}
