/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencias;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author danflovier
 */
public class MenuExpediente extends javax.swing.JFrame {
    
    public MenuExpediente() {
        initComponents();
        
        // Get the screen resolution of the device
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        
        // Set size of the JFrame
        this.setSize(screenWidth / 2 - 350, screenHeight - 450);
        
        // Set default close operation
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        
        // Set a background color to the JFrame
        this.getContentPane().setBackground(new Color(255,255,255));
        
        // Center the JFrame
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_logo = new javax.swing.JLabel();
        label_expediente = new javax.swing.JLabel();
        label_vigencia = new javax.swing.JLabel();
        label_academico = new javax.swing.JLabel();
        label_psicologico = new javax.swing.JLabel();
        label_medico = new javax.swing.JLabel();
        label_indisciplina = new javax.swing.JLabel();
        label_faltas = new javax.swing.JLabel();
        indisciplina = new javax.swing.JButton();
        historial_academico = new javax.swing.JButton();
        perfil_medico = new javax.swing.JButton();
        vigencia = new javax.swing.JButton();
        perfil_psicologico = new javax.swing.JButton();
        faltas = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        file_exit = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        about_rcsf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Residencias Santa Fe | Expediente");
        setBackground(new java.awt.Color(33, 150, 243));
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage());
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo5.png"))); // NOI18N
        getContentPane().add(label_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 180, 70));

        label_expediente.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        label_expediente.setForeground(new java.awt.Color(76, 76, 76));
        label_expediente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_expediente.setText("EXPEDIENTE");
        getContentPane().add(label_expediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 530, -1));

        label_vigencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_vigencia.setForeground(new java.awt.Color(76, 76, 76));
        label_vigencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_vigencia.setText("VIGENCIA");
        getContentPane().add(label_vigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 60, 20));

        label_academico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_academico.setForeground(new java.awt.Color(76, 76, 76));
        label_academico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_academico.setText("H. ACADÉMICO");
        getContentPane().add(label_academico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 110, 20));

        label_psicologico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_psicologico.setForeground(new java.awt.Color(76, 76, 76));
        label_psicologico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_psicologico.setText("P. PSICOlÖGICO");
        getContentPane().add(label_psicologico, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 120, 20));

        label_medico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_medico.setForeground(new java.awt.Color(76, 76, 76));
        label_medico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_medico.setText("PERFIL MÉDICO");
        getContentPane().add(label_medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 130, 20));

        label_indisciplina.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_indisciplina.setForeground(new java.awt.Color(76, 76, 76));
        label_indisciplina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_indisciplina.setText("INDISCIPLINA");
        getContentPane().add(label_indisciplina, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 100, 20));

        label_faltas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_faltas.setForeground(new java.awt.Color(76, 76, 76));
        label_faltas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_faltas.setText("FALTAS");
        getContentPane().add(label_faltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 60, 20));

        indisciplina.setBackground(new java.awt.Color(255, 255, 255));
        indisciplina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-red.png"))); // NOI18N
        indisciplina.setBorder(null);
        indisciplina.setBorderPainted(false);
        indisciplina.setContentAreaFilled(false);
        indisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indisciplinaActionPerformed(evt);
            }
        });
        getContentPane().add(indisciplina, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 80, 100));

        historial_academico.setBackground(new java.awt.Color(255, 255, 255));
        historial_academico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-blue.png"))); // NOI18N
        historial_academico.setBorder(null);
        historial_academico.setBorderPainted(false);
        historial_academico.setContentAreaFilled(false);
        historial_academico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historial_academicoActionPerformed(evt);
            }
        });
        getContentPane().add(historial_academico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 80, 100));

        perfil_medico.setBackground(new java.awt.Color(255, 255, 255));
        perfil_medico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-green.png"))); // NOI18N
        perfil_medico.setBorder(null);
        perfil_medico.setBorderPainted(false);
        perfil_medico.setContentAreaFilled(false);
        perfil_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfil_medicoActionPerformed(evt);
            }
        });
        getContentPane().add(perfil_medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 80, 100));

        vigencia.setBackground(new java.awt.Color(255, 255, 255));
        vigencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-green2.png"))); // NOI18N
        vigencia.setBorder(null);
        vigencia.setBorderPainted(false);
        vigencia.setContentAreaFilled(false);
        vigencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vigenciaActionPerformed(evt);
            }
        });
        getContentPane().add(vigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 80, 100));

        perfil_psicologico.setBackground(new java.awt.Color(255, 255, 255));
        perfil_psicologico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-purple.png"))); // NOI18N
        perfil_psicologico.setBorder(null);
        perfil_psicologico.setBorderPainted(false);
        perfil_psicologico.setContentAreaFilled(false);
        perfil_psicologico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfil_psicologicoActionPerformed(evt);
            }
        });
        getContentPane().add(perfil_psicologico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 80, 100));

        faltas.setBackground(new java.awt.Color(255, 255, 255));
        faltas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file-yellow.png"))); // NOI18N
        faltas.setBorder(null);
        faltas.setBorderPainted(false);
        faltas.setContentAreaFilled(false);
        faltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faltasActionPerformed(evt);
            }
        });
        getContentPane().add(faltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 80, 100));

        back.setBackground(java.awt.Color.white);
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(76, 76, 76));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back-button.png"))); // NOI18N
        back.setText("REGRESAR");
        back.setBorder(null);
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setMaximumSize(new java.awt.Dimension(129, 65));
        back.setMinimumSize(new java.awt.Dimension(129, 65));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 130, 40));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setBorderPainted(false);
        Menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        file.setText("File");
        file.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        file_exit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        file_exit.setText("Cerrar sesión");
        file_exit.setBorderPainted(true);
        file_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_exitActionPerformed(evt);
            }
        });
        file.add(file_exit);

        Menu.add(file);

        about.setText("About...");
        about.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        about_rcsf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        about_rcsf.setText("Residencias CSF");
        about_rcsf.setBorderPainted(true);
        about_rcsf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_rcsfActionPerformed(evt);
            }
        });
        about.add(about_rcsf);

        Menu.add(about);

        setJMenuBar(Menu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void about_rcsfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_rcsfActionPerformed
       new ResidenciasCSF().setVisible(true);
    }//GEN-LAST:event_about_rcsfActionPerformed

    private void file_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_exitActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_file_exitActionPerformed

    private void indisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indisciplinaActionPerformed
        new Indisciplinas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_indisciplinaActionPerformed

    private void historial_academicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historial_academicoActionPerformed
        new HistorialAcademico().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_historial_academicoActionPerformed

    private void perfil_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfil_medicoActionPerformed
        new HistorialMedico().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_perfil_medicoActionPerformed

    private void vigenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vigenciaActionPerformed
        new Informe().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_vigenciaActionPerformed

    private void perfil_psicologicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfil_psicologicoActionPerformed
        new PerfilPsicologico().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_perfil_psicologicoActionPerformed

    private void faltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faltasActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new MenuAlumnos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuExpediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu about;
    private javax.swing.JMenuItem about_rcsf;
    private javax.swing.JButton back;
    private javax.swing.JButton faltas;
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem file_exit;
    private javax.swing.JButton historial_academico;
    private javax.swing.JButton indisciplina;
    private javax.swing.JLabel label_academico;
    private javax.swing.JLabel label_expediente;
    private javax.swing.JLabel label_faltas;
    private javax.swing.JLabel label_indisciplina;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_medico;
    private javax.swing.JLabel label_psicologico;
    private javax.swing.JLabel label_vigencia;
    private javax.swing.JButton perfil_medico;
    private javax.swing.JButton perfil_psicologico;
    private javax.swing.JButton vigencia;
    // End of variables declaration//GEN-END:variables
}
