/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencias;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author danflovier
 */
public class PerfilPsicologico extends javax.swing.JFrame {
    Connection con;
    final private MySQL db;
    
    public PerfilPsicologico() {
        initComponents();
        
        // Set a background color to the JFrame
        this.getContentPane().setBackground(new Color(255,255,255));  
        

        db = new MySQL(); 
        initMatricula();
        
    }
    
    public void initMatricula(){
        con = db.MySQLConnection();
        String query = "{call getAlumnos()}";
        ResultSet result;
        try {
            CallableStatement st = con.prepareCall(query);
            result = st.executeQuery();
            while(result.next()){
                matricula.addItem(result.getString("Matricula"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Alumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    String imgPath = null;
    
    public ImageIcon ResizeImage(String ImagePath, byte[] pic){
        ImageIcon MyImage = null;
        if (ImagePath != null){
            MyImage = new ImageIcon(ImagePath);
        }
        else{
            MyImage = new ImageIcon(pic);
        }
        
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(documento.getWidth(),documento.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_login = new javax.swing.JLabel();
        label_logo = new javax.swing.JLabel();
        label_line = new javax.swing.JLabel();
        documento = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        upload = new javax.swing.JButton();
        back = new javax.swing.JButton();
        matricula = new javax.swing.JComboBox<>();
        label_buscar = new javax.swing.JLabel();
        label_nota1 = new javax.swing.JLabel();
        label_nota2 = new javax.swing.JLabel();
        label_nota3 = new javax.swing.JLabel();
        label_nota4 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        log_out = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        about_csf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Residencias Santa Fe | Perfil Psicológico");
        setBackground(new java.awt.Color(33, 150, 243));
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage());
        setPreferredSize(new java.awt.Dimension(884, 1000));
        setResizable(false);
        setSize(new java.awt.Dimension(884, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_login.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        label_login.setForeground(new java.awt.Color(76, 76, 76));
        label_login.setText("PERFIL PSICOLÓGICO");
        getContentPane().add(label_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        label_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo5.png"))); // NOI18N
        getContentPane().add(label_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 860, 180, 70));

        label_line.setBackground(new java.awt.Color(84, 172, 210));
        label_line.setForeground(new java.awt.Color(3, 169, 244));
        label_line.setOpaque(true);
        getContentPane().add(label_line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 790, 10));

        documento.setBackground(new java.awt.Color(201, 226, 253));
        documento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        documento.setForeground(new java.awt.Color(76, 76, 76));
        documento.setOpaque(true);
        getContentPane().add(documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 440, 600));

        agregar.setBackground(new java.awt.Color(255, 255, 255));
        agregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registrar.png"))); // NOI18N
        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 140, 40));

        buscar.setBackground(new java.awt.Color(255, 255, 255));
        buscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 160, 30));

        eliminar.setBackground(new java.awt.Color(255, 255, 255));
        eliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 140, 40));

        editar.setBackground(new java.awt.Color(255, 255, 255));
        editar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        editar.setText("EDITAR");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 140, 40));

        upload.setBackground(java.awt.Color.white);
        upload.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        upload.setForeground(new java.awt.Color(76, 76, 76));
        upload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upload.png"))); // NOI18N
        upload.setText("SUBIR DOCUMENTO");
        upload.setBorder(null);
        upload.setBorderPainted(false);
        upload.setContentAreaFilled(false);
        upload.setMaximumSize(new java.awt.Dimension(129, 65));
        upload.setMinimumSize(new java.awt.Dimension(129, 65));
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        getContentPane().add(upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 880, 180, 40));

        back.setBackground(java.awt.Color.white);
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(76, 76, 76));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back-button.png"))); // NOI18N
        back.setText("REGRESAR");
        back.setBorder(null);
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setMaximumSize(new java.awt.Dimension(129, 65));
        back.setMinimumSize(new java.awt.Dimension(129, 65));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 880, 120, 40));

        matricula.setBackground(new java.awt.Color(204, 204, 204));
        matricula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        matricula.setForeground(new java.awt.Color(76, 76, 76));
        matricula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        matricula.setBorder(null);
        matricula.setFocusable(false);
        matricula.setLightWeightPopupEnabled(false);
        matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaActionPerformed(evt);
            }
        });
        getContentPane().add(matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 240, 30));

        label_buscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_buscar.setForeground(new java.awt.Color(76, 76, 76));
        label_buscar.setText("MATRÍCULA DEL ALUMNO:");
        getContentPane().add(label_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        label_nota1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_nota1.setForeground(new java.awt.Color(76, 76, 76));
        label_nota1.setText("NOTA:");
        getContentPane().add(label_nota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, -1, -1));

        label_nota2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_nota2.setForeground(new java.awt.Color(76, 76, 76));
        label_nota2.setText("La imagen debe tener el formato");
        getContentPane().add(label_nota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, -1, -1));

        label_nota3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_nota3.setForeground(new java.awt.Color(76, 76, 76));
        label_nota3.setText(".JPG, .GIF o .PNG y debe tener un ");
        getContentPane().add(label_nota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, -1, -1));

        label_nota4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_nota4.setForeground(new java.awt.Color(76, 76, 76));
        label_nota4.setText("tamaño máximo de 64KB");
        getContentPane().add(label_nota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, -1, -1));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setBorder(null);
        Menu.setBorderPainted(false);
        Menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        file.setText("File");
        file.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        log_out.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        log_out.setText("Cerrar sesión");
        log_out.setBorderPainted(true);
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        file.add(log_out);

        Menu.add(file);

        about.setText("About...");
        about.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        about_csf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        about_csf.setText("Residencias CSF");
        about_csf.setBorderPainted(true);
        about_csf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_csfActionPerformed(evt);
            }
        });
        about.add(about_csf);

        Menu.add(about);

        setJMenuBar(Menu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        con = db.MySQLConnection();
        
        if (matricula.getSelectedItem() != "Seleccionar"){
            if (imgPath != null){
                String query = "{call registrarPPsicologico(?,?)}";  
                PreparedStatement ps;
                
                try {
                    ps = con.prepareStatement(query);
                    InputStream img = new FileInputStream(new File(imgPath));
                    
                    ps.setBlob(1,img);
                    ps.setString(2, matricula.getSelectedItem().toString());
                
                    if (ps.executeUpdate() == 1){
                        JOptionPane.showMessageDialog(null, "Imagen insertada");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(HistorialMedico.class.getName()).log(Level.SEVERE, null, ex);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(HistorialMedico.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Imagen NO seleccionada"); 
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Matrícula NO seleccionada"); 
        }
        imgPath = null;
    }//GEN-LAST:event_agregarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        con = db.MySQLConnection();
        
        if (matricula.getSelectedItem() != "Seleccionar"){
            try {
                ResultSet rs;
                PreparedStatement ps;
                String query = "{call buscarPPsicologico(?)}";
                
                ps = con.prepareStatement(query);
                ps.setString(1, matricula.getSelectedItem().toString());
                rs = ps.executeQuery();
                
                if(rs.next()){
                    documento.setIcon(ResizeImage(null, rs.getBytes("Perfil")));
                    
                    File image = new File("perfiles/" + "PP" + matricula.getSelectedItem() + ".png");
                    FileOutputStream fos = new FileOutputStream(image);
                    fos.write(rs.getBytes("Perfil"));
                    fos.close();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Perfil NO encontrado");  
                }
            
                rs.close();
                ps.close();
            } 
            catch (SQLException ex) {
                Logger.getLogger(PerfilPsicologico.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(PerfilPsicologico.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(PerfilPsicologico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Matrícula NO seleccionada"); 
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
       con = db.MySQLConnection();
        
        if (matricula.getSelectedItem() != "Seleccionar"){
            try {
                String query = "{call eliminarPPsicologico(?)}";  
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, matricula.getSelectedItem().toString());
                if(ps.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(null, "Perfil eliminado");
                }
                else{
                    JOptionPane.showMessageDialog(null, "No existe el ID del perfil");
                }
            } catch (SQLException ex) {
                Logger.getLogger(HistorialMedico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Matrícula NO seleccionada"); 
        }
        
        documento.setIcon(null);
    }//GEN-LAST:event_eliminarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        con = db.MySQLConnection();
        
        if (matricula.getSelectedItem() != "Seleccionar"){
            if(imgPath != null){
                try {
                    InputStream  img = new FileInputStream(imgPath);
                    String query = "{call editarPPsicologico(?,?)}";
                    PreparedStatement ps = con.prepareStatement(query);
                    ps.setBlob(1, img);
                    ps.setString(2, matricula.getSelectedItem().toString());
                    if(ps.executeUpdate() == 1){
                        JOptionPane.showMessageDialog(null, "Perfil actualizado");
                    }else{
                        JOptionPane.showMessageDialog(null, "No existe el ID del perfil.");
                    }
                } catch (Exception ex) {
                    Logger.getLogger(HistorialMedico.class.getName()).log(Level.SEVERE, null, ex);
                }            
            }else{
                JOptionPane.showMessageDialog(null, "Perfil no seleccionado");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Matrícula NO seleccionada"); 
        }
        imgPath = null;
    }//GEN-LAST:event_editarActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_log_outActionPerformed

    private void about_csfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_csfActionPerformed
        new ResidenciasCSF().setVisible(true);
    }//GEN-LAST:event_about_csfActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            documento.setIcon(ResizeImage(path,null));
            imgPath = path;
        }
        else if (result == JFileChooser.CANCEL_OPTION){
            System.out.println("Imagen NO seleccionada");
        }
    }//GEN-LAST:event_uploadActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new MenuExpediente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilPsicologico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilPsicologico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilPsicologico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilPsicologico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilPsicologico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu about;
    private javax.swing.JMenuItem about_csf;
    private javax.swing.JButton agregar;
    private javax.swing.JButton back;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel documento;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JMenu file;
    private javax.swing.JLabel label_buscar;
    private javax.swing.JLabel label_line;
    private javax.swing.JLabel label_login;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_nota1;
    private javax.swing.JLabel label_nota2;
    private javax.swing.JLabel label_nota3;
    private javax.swing.JLabel label_nota4;
    private javax.swing.JMenuItem log_out;
    private javax.swing.JComboBox<String> matricula;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables
}
