/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencias;

import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danflovier
 */
public class Personal extends javax.swing.JFrame {
    final private MySQL db; 
    Connection con;
    
    public Personal() {
        initComponents();
        
        // Set a background color to the JFrame
        this.getContentPane().setBackground(new Color(255,255,255));
        db = new MySQL();
        nomina.setEnabled(false);
        contrasena.setEnabled(false);
        initResidencias();
    }
    public void clearRegisterForm(){
        id.setText(null);
        nombre.setText(null);
        anio.setText(null);
        mes.setText(null);
        dia.setText(null);  
        sexo.setSelectedIndex(0);
        estado.setSelectedIndex(0);
        direccion.setText(null);
        puesto.setSelectedIndex(0);
        telefono.setText(null);
        correo_institucional.setText(null);
        nomina.setText(null);
        contrasena.setText(null);
    }
    
    
    private void initResidencias()
    {
        if(residencia.getItemCount() == 0)
            residencia.addItem("Seleccionar");
        Connection connect = db.MySQLConnection();
        String query = "{call getResidencias()}";
        ResultSet result;
        try 
        {
            CallableStatement call = connect.prepareCall(query);
            result = call.executeQuery();
            while(result.next())
            {
                residencia.addItem(result.getString("ID_residencia"));
            }
        } 
        catch (SQLException ex)
        {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_id = new javax.swing.JLabel();
        label_login = new javax.swing.JLabel();
        label_residencia = new javax.swing.JLabel();
        label_residencias = new javax.swing.JLabel();
        label_nombre = new javax.swing.JLabel();
        label_dia = new javax.swing.JLabel();
        label_mes = new javax.swing.JLabel();
        label_anio = new javax.swing.JLabel();
        label_estado = new javax.swing.JLabel();
        label_contrasena = new javax.swing.JLabel();
        label_direccion = new javax.swing.JLabel();
        label_telefono = new javax.swing.JLabel();
        label_correo = new javax.swing.JLabel();
        label_logo = new javax.swing.JLabel();
        label_puesto = new javax.swing.JLabel();
        label_buscar = new javax.swing.JLabel();
        label_line = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        anio = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        correo_institucional = new javax.swing.JTextField();
        nomina = new javax.swing.JTextField();
        contrasena = new javax.swing.JPasswordField();
        sexo = new javax.swing.JComboBox<>();
        estado = new javax.swing.JComboBox<>();
        puesto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_personal = new javax.swing.JTable();
        mostrar_todos = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        back = new javax.swing.JButton();
        label_nomina = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        label_admin = new javax.swing.JLabel();
        label_line3 = new javax.swing.JLabel();
        residencia = new javax.swing.JComboBox<>();
        label_sexo = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        log_out = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        about_csf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Residencias Santa Fe | Personal");
        setBackground(new java.awt.Color(33, 150, 243));
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage());
        setPreferredSize(new java.awt.Dimension(1500, 1000));
        setResizable(false);
        setSize(new java.awt.Dimension(1500, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_id.setForeground(new java.awt.Color(76, 76, 76));
        label_id.setText("ID");
        getContentPane().add(label_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        label_login.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        label_login.setForeground(new java.awt.Color(76, 76, 76));
        label_login.setText("PERSONAL");
        getContentPane().add(label_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        label_residencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_residencia.setForeground(new java.awt.Color(76, 76, 76));
        label_residencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_residencia.setText("RESIDENCIA");
        getContentPane().add(label_residencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 140, -1));

        label_residencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_residencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo5.png"))); // NOI18N
        getContentPane().add(label_residencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 910, 180, 70));

        label_nombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_nombre.setForeground(new java.awt.Color(76, 76, 76));
        label_nombre.setText("NOMBRE COMPLETO");
        getContentPane().add(label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        label_dia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_dia.setForeground(new java.awt.Color(76, 76, 76));
        label_dia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_dia.setText("DD");
        getContentPane().add(label_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 80, -1));

        label_mes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_mes.setForeground(new java.awt.Color(76, 76, 76));
        label_mes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_mes.setText("MM");
        getContentPane().add(label_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 80, -1));

        label_anio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_anio.setForeground(new java.awt.Color(76, 76, 76));
        label_anio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_anio.setText("AAAA");
        getContentPane().add(label_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 70, -1));

        label_estado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_estado.setForeground(new java.awt.Color(76, 76, 76));
        label_estado.setText("ESTADO");
        getContentPane().add(label_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 170, -1));

        label_contrasena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_contrasena.setForeground(new java.awt.Color(76, 76, 76));
        label_contrasena.setText("CONTRASEÑA");
        getContentPane().add(label_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 710, 310, -1));

        label_direccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_direccion.setForeground(new java.awt.Color(76, 76, 76));
        label_direccion.setText("DIRECCIÓN");
        getContentPane().add(label_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 380, -1));

        label_telefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_telefono.setForeground(new java.awt.Color(76, 76, 76));
        label_telefono.setText("TELÉFONO");
        getContentPane().add(label_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 240, -1));

        label_correo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_correo.setForeground(new java.awt.Color(76, 76, 76));
        label_correo.setText("CORREO INSTITUCIONAL");
        getContentPane().add(label_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 310, -1));

        label_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo5.png"))); // NOI18N
        getContentPane().add(label_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 820, 180, 70));

        label_puesto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_puesto.setForeground(new java.awt.Color(76, 76, 76));
        label_puesto.setText("PUESTO");
        getContentPane().add(label_puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 240, -1));

        label_buscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_buscar.setForeground(new java.awt.Color(76, 76, 76));
        label_buscar.setText("VER PERSONAL");
        getContentPane().add(label_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, -1, -1));

        label_line.setBackground(new java.awt.Color(250, 197, 28));
        label_line.setForeground(new java.awt.Color(3, 169, 244));
        label_line.setOpaque(true);
        getContentPane().add(label_line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 500, 10));

        id.setBackground(new java.awt.Color(223, 223, 223));
        id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        id.setToolTipText("");
        id.setBorder(null);
        id.setDoubleBuffered(true);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 200, 30));

        nombre.setBackground(new java.awt.Color(223, 223, 223));
        nombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nombre.setToolTipText("");
        nombre.setBorder(null);
        nombre.setDoubleBuffered(true);
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 580, 30));

        dia.setBackground(new java.awt.Color(223, 223, 223));
        dia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dia.setToolTipText("");
        dia.setBorder(null);
        dia.setDoubleBuffered(true);
        getContentPane().add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 80, 30));

        mes.setBackground(new java.awt.Color(223, 223, 223));
        mes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mes.setToolTipText("");
        mes.setBorder(null);
        mes.setDoubleBuffered(true);
        getContentPane().add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 80, 30));

        anio.setBackground(new java.awt.Color(223, 223, 223));
        anio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        anio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        anio.setToolTipText("");
        anio.setBorder(null);
        anio.setDoubleBuffered(true);
        getContentPane().add(anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 80, 30));

        telefono.setBackground(new java.awt.Color(223, 223, 223));
        telefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono.setToolTipText("");
        telefono.setBorder(null);
        telefono.setDoubleBuffered(true);
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 240, 30));

        correo_institucional.setBackground(new java.awt.Color(223, 223, 223));
        correo_institucional.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        correo_institucional.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        correo_institucional.setToolTipText("");
        correo_institucional.setBorder(null);
        correo_institucional.setDoubleBuffered(true);
        getContentPane().add(correo_institucional, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 310, 30));

        nomina.setBackground(new java.awt.Color(223, 223, 223));
        nomina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nomina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomina.setToolTipText("");
        nomina.setBorder(null);
        nomina.setDoubleBuffered(true);
        getContentPane().add(nomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 660, 310, 30));

        contrasena.setBackground(new java.awt.Color(223, 223, 223));
        contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contrasena.setBorder(null);
        contrasena.setEnabled(false);
        getContentPane().add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 740, 310, 30));

        sexo.setBackground(new java.awt.Color(204, 204, 204));
        sexo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sexo.setForeground(new java.awt.Color(76, 76, 76));
        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "M", "F" }));
        sexo.setBorder(null);
        sexo.setFocusable(false);
        sexo.setLightWeightPopupEnabled(false);
        getContentPane().add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 140, 30));

        estado.setBackground(new java.awt.Color(204, 204, 204));
        estado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        estado.setForeground(new java.awt.Color(76, 76, 76));
        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Ciudad de México", "Coahuila", "Colima", "Durango", "Estado de México", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas" }));
        estado.setBorder(null);
        estado.setFocusable(false);
        estado.setLightWeightPopupEnabled(false);
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 170, 30));

        puesto.setBackground(new java.awt.Color(204, 204, 204));
        puesto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        puesto.setForeground(new java.awt.Color(76, 76, 76));
        puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------", "Administrador" }));
        puesto.setBorder(null);
        puesto.setFocusable(false);
        puesto.setLightWeightPopupEnabled(false);
        puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoActionPerformed(evt);
            }
        });
        getContentPane().add(puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 240, 30));

        tabla_personal.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tabla_personal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "FECHA NACIMIENTO", "SEXO", "DIRECCION", "ESTADO", "TELÉFONO", "CORREO INSTITUCIONAL", "PUESTO"
            }
        ));
        jScrollPane1.setViewportView(tabla_personal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 690, 520));

        mostrar_todos.setBackground(new java.awt.Color(255, 255, 255));
        mostrar_todos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mostrar_todos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista.png"))); // NOI18N
        mostrar_todos.setText("MOSTRAR");
        mostrar_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrar_todosActionPerformed(evt);
            }
        });
        getContentPane().add(mostrar_todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 780, 180, 60));

        eliminar.setBackground(new java.awt.Color(255, 255, 255));
        eliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 780, 180, 60));

        registrar.setBackground(new java.awt.Color(255, 255, 255));
        registrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registrar.png"))); // NOI18N
        registrar.setText("REGISTRAR");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 800, 130, 40));

        cancelar.setBackground(new java.awt.Color(255, 255, 255));
        cancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 800, 140, 40));

        back.setBackground(java.awt.Color.white);
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(76, 76, 76));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back-button.png"))); // NOI18N
        back.setText("REGRESAR");
        back.setBorder(null);
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setMaximumSize(new java.awt.Dimension(129, 65));
        back.setMinimumSize(new java.awt.Dimension(129, 65));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 870, 130, 40));

        label_nomina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_nomina.setForeground(new java.awt.Color(76, 76, 76));
        label_nomina.setText("NÓMINA");
        getContentPane().add(label_nomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, 310, -1));

        direccion.setBackground(new java.awt.Color(223, 223, 223));
        direccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        direccion.setToolTipText("");
        direccion.setBorder(null);
        direccion.setDoubleBuffered(true);
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 380, 30));

        label_admin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_admin.setForeground(new java.awt.Color(76, 76, 76));
        label_admin.setText("ADMINISTRADOR");
        getContentPane().add(label_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 230, -1));

        label_line3.setBackground(new java.awt.Color(250, 197, 28));
        label_line3.setForeground(new java.awt.Color(3, 169, 244));
        label_line3.setOpaque(true);
        getContentPane().add(label_line3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 600, 210, 10));

        residencia.setBackground(new java.awt.Color(204, 204, 204));
        residencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        residencia.setForeground(new java.awt.Color(76, 76, 76));
        residencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "M", "F" }));
        residencia.setBorder(null);
        residencia.setFocusable(false);
        residencia.setLightWeightPopupEnabled(false);
        getContentPane().add(residencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 140, 30));

        label_sexo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_sexo.setForeground(new java.awt.Color(76, 76, 76));
        label_sexo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_sexo.setText("SEXO");
        getContentPane().add(label_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 140, -1));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setBorder(null);
        Menu.setBorderPainted(false);
        Menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        file.setText("File");
        file.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        log_out.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        log_out.setText("Cerrar sesión");
        log_out.setBorderPainted(true);
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        file.add(log_out);

        Menu.add(file);

        about.setText("About...");
        about.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        about_csf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        about_csf.setText("Residencias CSF");
        about_csf.setBorderPainted(true);
        about_csf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_csfActionPerformed(evt);
            }
        });
        about.add(about_csf);

        Menu.add(about);

        setJMenuBar(Menu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mostrar_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_todosActionPerformed
        // TODO add your handling code here:
        con = db.MySQLConnection();
        String query = "{call getPersonal()}";
        ResultSet result;
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Fecha de nacimiento");
        modelo.addColumn("Sexo");
        modelo.addColumn("Direccion");
        modelo.addColumn("Correo institucional");
        modelo.addColumn("Puesto");
        tabla_personal.setModel(modelo);
        
        String [] datosAlumno = new String[11];
        try {
            CallableStatement call = con.prepareCall(query);
            result = call.executeQuery();
            while(result.next()){
                datosAlumno[0] = result.getString("ID_personal");
                datosAlumno[1] = result.getString("Nombre");
                datosAlumno[2] = result.getDate("Fecha_nacimiento").toString();
                datosAlumno[3] = result.getString("Sexo");
                datosAlumno[4] = result.getString("Direccion");
                datosAlumno[5] = result.getString("Correo institucional");
                datosAlumno[6] = result.getString("Puesto");
                modelo.addRow(datosAlumno);
                tabla_personal.setModel(modelo);                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mostrar_todosActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        con = db.MySQLConnection();
        String query = "{ call eliminarPersonal(?) }";
        try {
            CallableStatement st = con.prepareCall(query);
            String idPersonal = (String) tabla_personal.getValueAt(tabla_personal.getSelectedRow(), 0);
            st.setString(1, idPersonal);
            st.executeQuery();
            mostrar_todos.doClick();
        } catch (SQLException ex) {
            Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        String query;
        Boolean res = true;
        String idPersonal = id.getText();
        String nombreA = nombre.getText();
        String fecha = anio.getText()+"-"+mes.getText()+"-"+dia.getText();  
        String sexoA = sexo.getSelectedItem().toString();
        String estadoA = estado.getSelectedItem().toString();
        String direction = direccion.getText();
        String puestoA = puesto.getSelectedItem().toString();
        String phone = telefono.getText();
        String correo = correo_institucional.getText();
        String residenciaA = residencia.getSelectedItem().toString();
        String nom = "";
        String pass = "";
        if(nomina.isEnabled() && contrasena.isEnabled()){
            nom = nomina.getText();
            pass = String.copyValueOf(contrasena.getPassword());
        }
        
        //JOptionPane.showConfirmDialog(null, "Este ", phone, WIDTH)
        con = db.MySQLConnection();
        CallableStatement st;
        
        if(res){
            query = "{ call insertarPersonal(?,?,?,?,?,?,?,?)}";
            try {
                st = con.prepareCall(query);
                st.setString(1,idPersonal);
                st.setString(2,nombreA);
                st.setDate(3,Date.valueOf(fecha));
                st.setString(4,sexoA);
                st.setString(5,puestoA);
                st.setString(6,direction);
                st.setString(7,correo);
                st.setString(8,residenciaA);
            st.executeQuery();
            JOptionPane.showMessageDialog(null, "Personal registrado correctamente", "Registro de personal", JOptionPane.INFORMATION_MESSAGE);
            clearRegisterForm();

            } catch (SQLException ex) {
                Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(!nom.equals("") && !pass.equals("")){
                query= "{ call agregarAdmin(?,?,?) }";
                try {
                    st = con.prepareCall(query);
                    st.setString(1, nom);
                    st.setString(2, pass);
                    st.setString(3, idPersonal);
                    st.executeQuery();
                } catch (SQLException ex) {
                    Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        
            
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        clearRegisterForm();
        if(!registrar.isEnabled())
            registrar.setEnabled(true);
    }//GEN-LAST:event_cancelarActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_log_outActionPerformed

    private void about_csfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_csfActionPerformed
        new ResidenciasCSF().setVisible(true);
    }//GEN-LAST:event_about_csfActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void puestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoActionPerformed
        if (puesto.getSelectedItem() == "Administrador"){
            nomina.setEnabled(true);
            contrasena.setEnabled(true);
        }
    }//GEN-LAST:event_puestoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu about;
    private javax.swing.JMenuItem about_csf;
    private javax.swing.JTextField anio;
    private javax.swing.JButton back;
    private javax.swing.JButton cancelar;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JTextField correo_institucional;
    private javax.swing.JTextField dia;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton eliminar;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JMenu file;
    private javax.swing.JTextField id;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_admin;
    private javax.swing.JLabel label_anio;
    private javax.swing.JLabel label_buscar;
    private javax.swing.JLabel label_contrasena;
    private javax.swing.JLabel label_correo;
    private javax.swing.JLabel label_dia;
    private javax.swing.JLabel label_direccion;
    private javax.swing.JLabel label_estado;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_line;
    private javax.swing.JLabel label_line3;
    private javax.swing.JLabel label_login;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_mes;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_nomina;
    private javax.swing.JLabel label_puesto;
    private javax.swing.JLabel label_residencia;
    private javax.swing.JLabel label_residencias;
    private javax.swing.JLabel label_sexo;
    private javax.swing.JLabel label_telefono;
    private javax.swing.JMenuItem log_out;
    private javax.swing.JTextField mes;
    private javax.swing.JButton mostrar_todos;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nomina;
    private javax.swing.JComboBox<String> puesto;
    private javax.swing.JButton registrar;
    private javax.swing.JComboBox<String> residencia;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JTable tabla_personal;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
